name: 'Setup Alire (self-built)'
description: 'Prepare Alire to be run in subsequent actions'
author: 'Alire Project'

inputs:
  toolchain:
    description: Arguments to pass to `alr toolchain` after setup
    required: false
    default: 'gnat_native gprbuild<2000'
  toolchain_dir:
    description: Location to install the toolchain under
    required: false
    default: ''

runs:
  using: 'composite'
  steps: 
    - name: Set up GNAT
      uses: ada-actions/toolchain@ce2020

    - name: Set up Alire
      uses: alire-project/setup-alire@latest-devel
      with:
        toolchain: ${{ toolchain }}
        toolchain_dir: ${{ toolchain_dir }}
