name: 'Setup Alire (self-built)'
description: 'Prepare Alire to be run in subsequent actions'
author: 'Alire Project'

inputs:
  toolchain:
    description: Arguments to pass to `alr toolchain` after setup
    required: false
    default: 'gnat_native gprbuild'
  toolchain_dir:
    description: Location to install the toolchain under
    required: false
    default: ''

runs:
  using: 'composite'
  steps: 
#    - name: Set up GNAT (FSF)
#      if: runner.os == 'Linux'
#      uses: ada-actions/toolchain@ce2021
#      with:
#        distrib: fsf
#
#    - name: Set up GNAT (CE)
#      if: runner.os != 'Linux'
#      uses: ada-actions/toolchain@ce2021
#      with:
#        distrib: community

    # Until conditionals work in composite actions, we are forced to use always
    # the CE edition
    - name: Set up GNAT (CE)
      uses: ada-actions/toolchain@ce2020 # 2020 required for macOS
      with:
        distrib: community

    - name: Set up Alire
      uses: alire-project/setup-alire@latest-devel
      with:
        toolchain: ${{ inputs.toolchain }}
        toolchain_dir: ${{ inputs.toolchain_dir }}
