name: 'Setup Alire'
description: 'Prepare Alire to be run in subsequent actions'
author: 'Alire Project'

inputs:
  toolchain:
    description: Arguments to pass to `alr toolchain` after setup
    required: false
    default: 'gnat_native gprbuild<2000'
  toolchain_dir:
    description: Location to install the toolchain under
    required: false
    default: ''

runs:
  using: 'node12'
  main: 'lib/main.js'
