name: 'Alire Setup'
description: 'Install Alire package manager'
author: 'Alire Project'

inputs:
  version:
    description: Use this argument to install a stable or nightly release. Use a version number without v prefix, e.g., 1.0.1, 1.1.0, or 'nightly'. This argument will be ignored if a branch argument is supplied. Defaults to the latest stable release.
    required: false
    default: '2.0.0'
    # Also to be updated in test-cache-yml
  branch:
    description: Use this argument to install a development branch (e.g., master). Using this option will require a preexisting compiler in the workflow environment.
    required: false
    default: ''
  toolchain:
    description: Arguments to pass to `alr toolchain` after setup.
    required: false
    default: 'gnat_native gprbuild'
  cache:
    description: Whether to reuse a cached previous install.
    required: false
    default: true

outputs:
  cache_hit:
    description: Whether a cached installation was reused
    value: ${{ steps.cache-alr.outputs.cache-hit }}

runs:
  using: "composite"
  steps:

    - name: Identify hash from which alr was built
      # Identifies the version and hash to be used for the cache key
      id: find-hash
      shell: bash
      run: |
        if [[ "${{ inputs.branch }}" != "" ]]; then
          echo "hash=$(git ls-remote --heads https://github.com/alire-project/alire ${{ inputs.branch }} | cut -f1)" >> $GITHUB_OUTPUT
          echo "version=${{ inputs.branch }}" >> $GITHUB_OUTPUT
        elif [[ "${{ inputs.version }}" != "nightly" ]]; then
          echo "hash=$(git ls-remote --tags https://github.com/alire-project/alire v${{ inputs.version }} | cut -f1)" >> $GITHUB_OUTPUT
          echo "version=${{ inputs.version }}" >> $GITHUB_OUTPUT
        else
          echo "hash=$(git ls-remote --tags https://github.com/alire-project/alire ${{ inputs.version }} | cut -f1)" >> $GITHUB_OUTPUT
          echo "version=${{ inputs.version }}" >> $GITHUB_OUTPUT
        fi

    - name: Print cache key
      id: cache-key
      shell: bash
      run: |
        echo "key=alr[${{ steps.find-hash.outputs.version }}][${{ inputs.toolchain }}][${{ runner.os }}][${{ steps.find-hash.outputs.hash }}]" >> $GITHUB_OUTPUT

    - name: Reuse cached installation
      if: ${{ inputs.cache == 'true' && inputs.toolchain_dir == '' }}
      id: cache-alr
      uses: actions/cache/restore@v3
      with:
        path: |
          ~/.cache/alire
          ~/.config/alire
          ./alire_install
        key: ${{steps.cache-key.outputs.key}}
        # .cache contains msys64 install on Windows
        # .config contains the toolchain at the default location, besides index config
        # ./alire_install contains alr itself

    - name: Check cache output
      shell: bash
      run: |
        echo Cache hit result: [${{steps.cache-alr.outputs.cache-hit}}] cache-key: ${{steps.cache-key.outputs.key}}

    # Ascertain if we need to install a toolchain for building from sources
    - name: Find GNAT
      shell: bash
      id: find-gnat
      run: gnat --version && echo "available=true" >> $GITHUB_OUTPUT || echo "available=false" >> $GITHUB_OUTPUT

    # Setup a GNAT if necessary to build from branch. We cannot use alr-install
    # as that creates infinite recursion. Rather than relying on the old action
    # that sets up CE editions, we simply fetch a stable alr capable of running
    # `alr install`, and we use that to install the latest FSF GNAT.

    # BEGIN TOOLCHAIN INSTALLATION

    - name: Identify need for GNAT
      if: inputs.branch != '' && steps.find-gnat.outputs.available != 'true' && steps.cache-alr.outputs.cache-hit != 'true'
      id: need-GNAT
      shell: bash
      run: echo "need=true" >> $GITHUB_OUTPUT

    - name: Install GNAT (I) Linux
      if: steps.need-GNAT.outputs.need == 'true' && runner.os == 'Linux'
      uses: engineerd/configurator@v0.0.10
      with:
        name: alr
        url: https://github.com/alire-project/alire/releases/download/v2.0.0/alr-2.0.0-bin-x86_64-linux.zip
        pathInArchive: bin/alr
    - name: Install GNAT (I) macOS
      if: steps.need-GNAT.outputs.need == 'true' && runner.os == 'macOS'
      uses: engineerd/configurator@v0.0.10
      with:
        name: alr
        url: https://github.com/alire-project/alire/releases/download/v2.0.0/alr-2.0.0-bin-x86_64-macos.zip
        pathInArchive: bin/alr
    - name: Install GNAT (I) Windows
      if: steps.need-GNAT.outputs.need == 'true' && runner.os == 'Windows'
      uses: engineerd/configurator@v0.0.10
      with:
        name: alr.exe
        url: https://github.com/alire-project/alire/releases/download/v2.0.0/alr-2.0.0-bin-x86_64-windows.zip
        pathInArchive: bin/alr.exe

    - name: Install GNAT (II)
      if: steps.need-GNAT.outputs.need == 'true'
      shell: bash
      run: |
        alr install gnat_native gprbuild --prefix=$PWD/setup_alire_prefix
        echo REMOVAL TARGET: $(which alr)
        rm -f $(which alr)* && echo REMOVED stable alr used for toolchain install

    - name: Install GNAT (III) - Add to path (Windows)
      if: steps.need-GNAT.outputs.need == 'true' && runner.os == 'Windows'
      shell: pwsh
      run: |
        $Target = Resolve-Path .\setup_alire_prefix\bin
        Add-Content $env:GITHUB_PATH $Target

    - name: Install GNAT (III) - Add to path (!Windows)
      if: steps.need-GNAT.outputs.need == 'true' && runner.os != 'Windows'
      shell: bash
      run: |
        readlink -f "$PWD/setup_alire_prefix/bin" >> $GITHUB_PATH

    # END TOOLCHAIN INSTALLATION

    # To run the old setup action which is javascript
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 16

    # Install alr. If found cached it will return without reinstalling (but setting PATH).
    # We forward inputs as they're bugged for JS in composite actions.

    - run: node $(echo "${{ github.action_path }}/lib/main.js" | sed 's/\\/\//g') '${{ toJSON(inputs) }}'
      shell: bash
      # on Windows, backlashes mess things for bash, and powershell chokes on toJSON output

    # Remove our installed toolchain as not to interfere with other
    # actions/workflows down the line
    - name: Remove GNAT (IV)
      if: steps.need-GNAT.outputs.need == 'true'
      shell: bash
      run: |
        rm -rf setup_alire_prefix && echo REMOVED toolchain used to build alr

    # Display result for the record
    - shell: bash
      run: |
        which alr
        alr --version

    # Save cache early so we can verify its proper working in a test workflow. Otherwise
    # it's not saved until workflow completion and by then it's too late.
    # When cache was hit, attempting to save will fail and emit a warning, so avoid it.
    - name: Cache install
      if: ${{ inputs.cache == 'true' && inputs.toolchain_dir == '' && steps.cache-alr.outputs.cache-hit != 'true' }}
      uses: actions/cache/save@v3
      with:
        path: |
          ~/.cache/alire
          ~/.config/alire
          ./alire_install
        key: ${{ steps.cache-alr.outputs.cache-primary-key }}
