# Changes to the v2 branch must be proposed via PRs in the branch
# v2-next. This way we can check the action just as GHA is going to
# use it.

name: Sanity check for PRs

on:
  pull_request:

jobs:
  sanity-check:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check PR comes from proper branch
        if: github.head_ref != 'v2-next'
        uses: actions/github-script@v3
        with:
          script: |
            core.setFailed(`PRs for ${{github.base_ref}} must come from v2-next, but branch is ${{github.head_ref}}`)

      - name: Check action itself
        uses: alire-project/setup-alire@v2-next

      - run: alr -n version
