# Changes to the v1 branch must be proposed via PRs in the branch
# v1-next. This way we can check the action just as GHA is going to
# use it.

name: Sanity check for PRs

on: pull_request

jobs:
  sanity-check:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check on proper branch
        if: github.head_ref != 'v1-next'
        uses: actions/github-script@v3
        with:
          script: |
            core.setFailed(`PRs for latest-stable must come from v1-next, but branch is ${{ github.head_ref }}`)

      - name: Check latest stable
        uses: alire-project/setup-alire@v1-next

      - run: alr -n version

      - name: Check nightly
        uses: alire-project/setup-alire@v1-next
        with:
          version: 'nightly'

      - run: alr -n version
