# Changes to the v1 branch must be proposed via PRs in the branch
# v1-next. This way we can check the action just as GHA is going to
# use it.

name: Sanity check for PRs

on: pull_request

jobs:
  sanity-check:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check on proper branch
        if: github.head_ref != 'v2-next'
        uses: actions/github-script@v3
        with:
          script: |
            core.setFailed('PRs for latest-stable@v2 must come from v2-next')

      - uses: alire-project/setup-alire@v2-next

      - run: alr -n version
