# Changes to the latest-stable branch must be proposed via PRs in the branch
# next-latest-stable. This way we can check the action just as GHA is going to
# use it.

name: Sanity check for PRs

on: pull_request

jobs:
  sanity-check:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check on proper branch
        if: github.head_ref != 'next-latest-stable'
        uses: actions/github-script@v3
        with:
          script: |
            core.setFailed('PRs for latest-stable must come from next-latest-stable')

      - uses: alire-project/setup-alire@next-latest-stable

      - run: alr -n version
