name: Sanity check for pushes

on: 
  push:
    branches:
      - latest-stable

jobs:
  sanity-check:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: alire-project/setup-alire@latest-stable
      - run: alr version
