name: Sanity check

on: pull_request

jobs:
  sanity-check:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      # setup-alire@latest-devel requires a GNAT compiler
      - uses: ada-actions/toolchain@ce2020
        with: 
           distrib: community # fsf fails on Windows

      - uses: alire-project/setup-alire@latest-devel

      - run: alr version
