# Changes to the latest-devel branch must be proposed via PRs in the
# next-latest-devel branch.

name: Sanity check

on: pull_request

jobs:
  sanity-check:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check on proper branch
        if: github.head_ref != 'next-latest-devel-self-build'
        uses: actions/github-script@v3
        with:
          script: |
            core.setFailed('PRs for latest-devel must come from next-latest-devel')

      - uses: alire-project/setup-alire@next-latest-devel-self-build

      - run: alr -n version
