# Changes to the v2 branch must be proposed via PRs in the branch
# v2-next. This way we can check the action just as GHA is going to
# use it.

name: Selftest

on: pull_request

jobs:
  setup-alire:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        target: [stable, nightly, source]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check on proper branch
        if: github.head_ref != 'v2-next'
        uses: actions/github-script@v3
        with:
          script: |
            core.setFailed(`PRs for latest-stable must come from v2-next, but branch is ${{ github.head_ref }}`)

      - name: Setup stable
        uses: alire-project/setup-alire@v2-next
        if: matrix.target == 'stable'
        with:
          cache: false 
          # We test without cache, as caching is tested in a separate workflow.
          # This way we make sure the cache isn't hiding any issue.

      - name: Setup nightly
        uses: alire-project/setup-alire@v2-next
        if: matrix.target == 'nightly'
        with:
          version: nightly
          cache: false

      - name: Setup from source
        uses: alire-project/setup-alire@v2-next
        if: matrix.target == 'source'
        with:
          branch: master
          cache: false

      # Verify proper builds

      - run: alr -n version | grep "os:" | grep LINUX
        if: matrix.os == 'ubuntu-latest'
        shell: bash

      - run: alr -n version | grep "os:" | grep MACOS
        if: matrix.os == 'macos-latest'
        shell: bash

      - run: alr -n version | grep "os:" | grep WINDOWS
        if: matrix.os == 'windows-latest'
        shell: bash
